name: Smart Contract Tests
on: [push]

jobs:
  tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - run: node scripts/generateAMPSkips.js 1 10 24
      - run: npx hardhat compile
      - run: npx hardhat size-contracts
      - run: npm run solhint
      - run: npx hardhat test
        env:
          REPORT_GAS: "1"
      - run: npx hardhat coverage
